language: java
before_install:
- sudo apt-get install jmeter
- jmeter=which jmeter
- ls /home/travis
- $jmeter -g D:\\apache-jmeter-3.2\\apacher-3.2\\bin\\result.jtl -o  C:\\Users\\sandesh\\Desktop\\dm1
- echo "$PATH"
install: true

#before_script : 
#- cd /d D:\apache-jmeter-3.2\apache-jmeter-3.2\bin
#- jmeter -g D:\\apache-jmeter-3.2\\apacher-3.2\\bin\\result.jtl -o  C:\\Users\\sandesh\\Desktop\\dm1
cache:
  directories:
    - $HOME/.m2
   
jdk: oraclejdk8

#env:
# - TEST_SUITE=units
# - TEST_SUITE=integration
matrix:
  include:
  - jdk: oraclejdk8
    env: TEST_SUITE=First Suite
 # - JMETER_VERSION: 3.0
  #  env: TEST_SUITE=New
     
  allow_failures:
  - jdk: 8
    env: TEST_SUITE=New

script: 
#- mvn -f ${TRAVIS_BUILD_DIR}/TestNgCommand1/pom.xml clean test compile package
- echo "$TRAVIS_BUILD_DIR"
- rm -rf results && mkdir results
- apache-jmeter-3.0/bin/jmeter.sh

notifications:
  email: sandesh.gadekar@mobiliya.com

branches:
  only:
  - master

git:
  depth: 3
  submodules: false
