language: java
install: true

#before_script : 
#- cd /d D:\apache-jmeter-3.2\apache-jmeter-3.2\bin
#- jmet-jmeteer -g D:\\apache-jmeter-3.2\\apacher-3.2\\bin\\result.jtl -o  C:\\Users\\sandesh\\Desktop\\dm1
cache:
  directories:
    - $HOME/.m2
   
jdk: oraclejdk8

#env:
# - TEST_SUITE=units
# - TEST_SUITE=integration
matrix:
  include:
  - jdk: oraclejdk8
    env: TEST_SUITE=First Suite
#  - jdk: 8
#    env: TEST_SUITE=New
     
  allow_failures:
  - jdk: 8
    env: TEST_SUITE=New

script: 
- ./mvnw test  ${TRAVIS_BUILD_DIR}/TestNgCommand1/src/TestClass/NewTest.java
- echo "$TRAVIS_BUILD_DIR"

notifications:
  email: sandesh.gadekar@mobiliya.com

branches:
  only:
  - master

git:
  depth: 3
  submodules: false
