language: java
install: true

cache:
  directories:
    - $HOME/.m2
   
jdk: oraclejdk8

matrix:
  include:
  - jdk: oraclejdk8
    env: TEST_SUITE=First Suite
  - jdk: oraclejdk7
    env: TEST_SUITE=New

  allow_failures:
  - jdk: oraclejdk7
    env: TEST_SUITE=New


script:
- mvn -f ${TRAVIS_BUILD_DIR}/TestNgCommand1/pom.xml clean test compile package
- echo "$home_loc"

notifications:
  email: sandesh.gadekar@mobiliya.com

branches:
  only:
  - master

git:
  depth: 3


