language: java
cache:
  directories:
    - $HOME/.m2
   
jdk: oraclejdk8

script: mvn -q clean install surefire:test -Dtest.includes=D:\\GitEclipse\\TestNG\\TestNgCommand1\\src\\TestClass\\NewTest.java