language: java
install: true

cache:
  directories:
    - $HOME/.m2
   
jdk: oraclejdk8


script:
- mvn -f ${TRAVIS_BUILD_DIR}/TestNgCommand1/pom.xml clean test compile package
- echo "$home_loc"

matrix:
  include:
  - jdk: "Test"
    env: TEST_SUITE=First Suite
  - jdk: "QA"
    env: TEST_SUITE=New

notifications:
  email: sandesh.gadekar@mobiliya.com

branches:
  only:
  - master

git:
  depth: 3

